name: Jason M Design - We Do Web
markdown: kramdown
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /blog/:title/
paginate: 5
paginate_path: "/blog/page:num/"
collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
  testimonials:
    output: false
gems: [jekyll-paginate]
